### ISSUE TITLE
P1 domain-aware exact polynomial factorization: verified occurrences, search integration and independent certificates

### ISSUE THREAD

**Issue by carstenartur** [carstenartur/Regelsuche#763]
## Status 2026-09-17 — univariate implementation delivered

The domain-aware exact univariate Z[x]/Q[x] implementation, occurrence-local transport and independent certification foundation are delivered. The ten remaining historical checklist entries were integration/evaluation obligations already owned by #748; they are now explicitly consolidated there instead of keeping two umbrella issues open. Advanced multivariate/LLL research is separately tracked in #1022.

## Active status — 2026-09-17

Delivered univariate factorization/occurrence/certificate work is retained as ✅ facts; only unchecked cache/mining/evaluation items remain active.

## Status 2026-09-17

The exact univariate Z[x]/Q[x] factorization, nested occurrence transport and independent certification foundation is largely delivered (**58 completed checklist items**). The remaining core work is now limited to verifier-authorized macro/cache/mining integration and the frozen #748 matched-work evaluation.

Five speculative advanced-factorization items were moved to https://github.com/carstenartur/Regelsuche/issues/1022; they no longer block closure of this univariate integration issue.

## Goal

Complete the product and evidence boundary around Regelsuche's domain-aware exact polynomial factorization subsystem.

The mathematical core supports a declared bounded univariate fragment over `Z[x]` and `Q[x]`. Verified root and nested occurrence transformations are merged, together with bounded, algorithmically independent original-domain irreducibility and complete-decomposition certificates. The remaining product work is to:

1. integrate on-demand execution, occurrence replay and verifier-derived macros through one shared transformation identity;
2. route eligible learned/mined polynomial identities through the typed theory boundary;
3. qualify search utility under the matched information and work contracts in #748.

There are no external users whose source or binary compatibility constrains this redesign. Historical experiment artifacts retain their frozen identities; current production APIs may be changed when that yields a clearer mathematical, occurrence, resource or trust boundary.

## Current state — 7 September 2026

Merged on `main`: root transformation #780, nested occurrence integration #802, independent original-domain irreducibility #940 and independent decomposition completeness #941. The original root pipeline remains:

```text
ExpressionParser.parseExactTerm
  -> ExactParsedTerm with parser-issued literal provenance
  -> ExactParsedUnivariatePolynomialView
  -> SparsePolynomial<ExactRational> in an explicit PolynomialRing
  -> FactorizationRequest with one non-resettable work authority
  -> selected FactorizationEngine proposal
       native Z[x]/Q[x]
         content / primitive part
         derivative / GGT / square-free layers
         deterministic suitable-prime campaign
         complete Berlekamp factorization in F_p[x]
         multifactor Hensel lifting to p^k
         bounded deterministic Zassenhaus recombination
         exact rational reassembly
       optional pinned GraalPy/SymPy proposal backend
  -> FactorizationVerifier
  -> exact source-product reconstruction
  -> explicitly selected verifier-issued candidate
  -> deterministic exact factor rendering
  -> exact reparse and ring reconstruction
  -> verifier-bound root-occurrence transformation or NO_CHANGE
```

The authoritative parser handoff is merged as #779. Exact coefficients are not recovered from `double`, rendered text or a parallel rational-polynomial model.

PR #780 was merged as `bc992a3811b8b202b31da533341a4770f62a4007`. The root-occurrence path now retains source-evidence continuity, explicit multi-candidate selection, parser-compatible digit and output limits, exact rational rendering, exact reparse, ring/polynomial reconstruction, one continued work ledger and a structural `NO_CHANGE` guard that prevents identity edges.

`FactorizationVerifier` independently proves exact product equality and request/work consistency. With explicitly requested `INDEPENDENT_COMPLETE` evidence, #940 certifies source irreducibility by a direct degree-one proof or a degree-preserving modular Rabin/Frobenius witness. #941 additionally certifies every nonconstant factor of a verified decomposition with remainder one before issuing `COMPLETE_FACTORIZATION`. Backend claims remain insufficient. Missing witnesses or exhausted work remain inconclusive.

The matched-information utility study remains tracked in #748. Its 600 execution inputs were frozen by #818; subsequent adapter, result-contract and measurement slices do not establish completion of the 30-run study or a search advantage. Nested occurrence support and bounded independent certification are delivered product capabilities, separately from that uncompleted utility qualification.

## Implemented slices

- #764 — coefficient domains, polynomial rings, canonical sparse polynomials, engine SPI, verifier and quartic migration;
- #765 — lossless univariate view, structural limits, derivative/division, GGT and characteristic-zero square-free decomposition;
- #766 — exact content and primitive-part normalization for `Z[x]` and `Q[x]`;
- #767 — explicit prime fields, deterministic Berlekamp factorization and finite-field reconstruction/irreducibility checks;
- #768 — deterministic suitable-prime selection with retained rejection reasons and source-bound evidence;
- #769 — central architecture, limits and claim-boundary documentation;
- #771 — bounded multifactor Hensel lifting with verified CRT corrections and one continued ledger;
- #772 — optional pinned GraalPy/SymPy proposal engine behind the same verifier boundary;
- #778 — bounded Zassenhaus recombination, exact rational reassembly, native general univariate engines and capability-matched SymPy comparison;
- #779 — parser-issued exact provenance routed directly into the authoritative `Q[x]` request/engine/verifier path;
- #780 — verifier-bound exact root transformation with deterministic rendering, exact reparse, ring reconstruction, candidate selection and one continued authority;
- #802 — nested occurrence pipeline using parser-issued ranges, shared `TreePosition` replacement, unchanged surrounding-node identity and accounted replay;
- #940 — independent bounded original-domain irreducibility certification;
- #941 — independent complete-decomposition certification after exact product verification.

## A. Mathematical and trust core — delivered

- ✅ Explicit exact coefficient-domain contract with stable IDs and arithmetic capabilities.
- ✅ Authoritative integer and exact-rational domains.
- ✅ Explicit prime fields and immutable polynomial-ring identity.
- ✅ Canonical immutable sparse polynomials and shared univariate coefficient view.
- ✅ Typed `FactorizationRequest` with structural, candidate and total-work limits.
- ✅ Backend-neutral `FactorizationEngine`; proposals and backend claims remain untrusted.
- ✅ `FactorizationVerifier` is the sole issuer of trusted decomposition candidates and reports.
- ✅ Exact product reconstruction and fail-closed ring/request/work validation.
- ✅ Native bounded univariate `Z[x]`/`Q[x]` factorization through rational reassembly.
- ✅ Optional pinned external proposal backend under the same verifier boundary.
- ✅ Theory-subsumption classification and bounded verifier/theory-derived macro cache outside the kernel.

## B. Exact parser boundary — delivered by #779

- ✅ Parser-issued literal provenance resolves coefficients and exponents by node identity.
- ✅ Direct `ExactParsedTerm` to `SparsePolynomial<ExactRational>` extraction.
- ✅ No render/reparse or `double` recovery before factorization.
- ✅ Exact bounded addition, subtraction, commutative multiplication, constant division and non-negative integer powers.
- ✅ Fail-closed multiple-variable, function, divisor, provenance and resource boundaries.
- ✅ Extraction work is consumed before only the remaining work enters the request.
- ✅ Zero, constant, unsupported and exhausted inputs do not invoke an engine.
- ✅ End-to-end native `Q[x]` factorization through `FactorizationVerifier`.

## C. Root-occurrence verified transformation — delivered by #780

- ✅ Bind one root `ExactParsedTerm` occurrence to extraction, request, engine report and selected verifier candidate.
- ✅ Validate source text, literal ranges, lexemes, exact values, value IDs and parser certificates under accounted work.
- ✅ Require explicit candidate selection when a report contains several candidates.
- ✅ Render unit, ordered factors, multiplicities and an allowed unresolved remainder deterministically.
- ✅ Render rationals only as exact integers or explicit numerator/denominator syntax.
- ✅ Enforce factor, cumulative-term, exponent, coefficient-bit, parser-digit, output and renderer-work limits.
- ✅ Parse the rendered expression again through `parseExactTerm`.
- ✅ Re-extract and require exact equality in the original coefficient domain and ring.
- ✅ Preserve backend claims without upgrading them to independent certificates.
- ✅ Return `NO_CHANGE`, not a search edge, when the reparsed AST is structurally identical to the source AST.
- ✅ Keep rejected rendered syntax diagnostic-only; expose `transformedExpression` solely for a fully reconstructed changed result.
- ✅ Bind source validation, factorization, rendering, reparse, reconstruction and structural comparison into the original total-work authority.
- ✅ Characterize complete, partial, no-candidate, backend-irreducible, unsupported, budget, forged-evidence and deterministic cases.
- ✅ Qualify the exact final head through checkout-owned Gradle and complete Maven/product/Docker verification.

## D. Nested occurrence integration — delivered by #802

The pipeline extends the same authority to a selected nested AST occurrence, using `TreePosition`, parser-issued source ranges and the shared staleness-guard/local-rewrite infrastructure. See [the occurrence contract](https://github.com/carstenartur/Regelsuche/blob/main/docs/exact-nested-factorization-transformation.md). The shared production search/cache integration remains section F.

### Occurrence and source contract

- ✅ Accept one parser-issued exact root, one `TreePosition` and one explicitly selected subtree occurrence.
- ✅ Navigate by path and reject missing or stale positions before factorization.
- ✅ Use exact node-bound literal evidence for the selected subtree; `TreePosition.text` may remain a display/staleness snapshot but must never authorize a numeric value.
- ✅ Bind root identity, path, exact subtree snapshot and source evidence into one occurrence certificate.
- ✅ Preserve the original root source separately from the canonical replacement rendering.
- ✅ Define the minimum parser range/projection extension needed for nested syntax without reintroducing a parallel AST.

### Execution and replacement

- ✅ Project the selected subtree into the existing exact parser/view/request/verifier pipeline without `double` recovery.
- ✅ Reuse #780's renderer, reparse, ring reconstruction and `NO_CHANGE` semantics.
- ✅ Replace only the selected path through shared local-rewrite structural replacement.
- ✅ Verify the selected path still identifies the authorized subtree at application time.
- ✅ Retain the unchanged surrounding AST and exact evidence separately from replacement evidence.
- ✅ Reject a replacement that changes a different occurrence, loses the path or cannot be replayed.

### Resource and evidence contract

- ✅ Continue one total-work authority across path validation, subtree projection, factorization, rendering, reparse, replacement and replay validation.
- ✅ Bound root visits, subtree visits, path depth, rendered output and replacement work explicitly.
- ✅ Issue one stable transformation identity usable by search, Workbench, graph and replay surfaces.
- ✅ Characterize repeated equal subtrees at different paths, stale paths, root/nested parity, rational literals, forged evidence and deterministic replay.

## E. Independent original-domain certification — bounded slice delivered by #940 and #941

Exact product verification is already independent of the engine. Completeness and irreducibility in the original domain require additional mathematics and must remain separately named.

The delivered bounded certificate uses a **sufficient modular witness**, not a decision-complete irreducibility procedure:

- normalize one candidate factor to a primitive integer associate;
- choose a deterministic prime that preserves degree and does not annul the leading coefficient;
- reduce independently modulo that prime;
- prove the reduction irreducible through an independently executed Rabin/Frobenius criterion;
- apply the degree-preserving irreducible-reduction theorem and Gauss's lemma;
- bind normalization, prime, reduction, checkpoints, work and request/candidate identity into issuer-owned evidence.

Requirements:

- ✅ Do not reuse an engine's irreducibility claim, selected prime or certificate as independent authority.
- ✅ Linear factors may receive a direct exact certificate.
- ✅ A complete decomposition requires exact product equality, remainder one and an independent certificate for every nonconstant factor.
- ✅ Source irreducibility may be issued only for the original request polynomial, never merely because a bounded search found no factor.
- ✅ Failure to find a witness remains `BUDGET_INCONCLUSIVE` or unsupported; it is not evidence of reducibility.
- ✅ Preserve the existing `VERIFIED_DECOMPOSITION` behavior when independent evidence was not requested.
- ✅ Characterize primitive/nonprimitive integer factors, rational normalization, unlucky primes, degree loss, reducible reductions, witness absence, work exhaustion and forged evidence.

A modular-witness implementation is intentionally incomplete: some irreducible rational polynomials may have no irreducible reduction among the bounded tested primes, or no irreducible reduction of the required cycle type at all. Universal irreducibility or CAS parity must not be claimed.

## F. Search, cache and learning integration

Owned jointly with #748:

- [ ] Expose one transformation identity shared by on-demand execution, nested replay and verifier-derived macros.
- [ ] Ensure a cached macro expands to the same verifier-authorized primitive transformation rather than becoming an unexplained shortcut.
- [ ] Route eligible learned/mined polynomial identities through the typed theory classifier after formation.
- [ ] Divert theory-subsumed instances to the bounded derived cache rather than the kernel or standard inventory.
- [ ] Keep direct factorization, cached replay, specialized quartic control, optional external backend and no-factorization profiles separately identifiable and ablatable.
- [ ] Execute the frozen matched-information/work comparison defined in #748.

## G. Qualification and comparative evidence

- ✅ Freeze a corpus stratified by domain, degree, coefficient size, density, multiplicity, reducible/irreducible status, reuse and occurrence depth under #748.
- ✅ Include positive, negative, unsupported, near-miss and budget-inconclusive cases in the frozen #748 corpus/qualification pair.
- [ ] Report factorization, source validation, rendering/reparse, occurrence replacement, cache lookup and replay work separately.
- [ ] Compare native, optional external and no-factorization profiles under explicit information and work parity.
- [ ] Reproduce canonical evidence in two clean checkout runs and one pinned-container run.
- [ ] Retain null and negative results.

## H. Later expansion

Only after the univariate product/evidence boundary is qualified:

The sparse representation already supports several variables; this does not implement multivariate factorization.

## No compatibility constraint

Do not retain obsolete constructors, nested records, string adapters, status enums or package locations solely because they existed in 0.3.0 or on an unmerged branch. Keep an adapter only when a retained experiment or external serialization format owns it, identify that owner and remove it when the migration completes.

The specialized `PolynomialDecompositionSynthesisOperator` remains a named historical/specialized control, not the general public factorization authority.

## Claim boundary

The merged architecture establishes bounded exact univariate factorization, exact product verification, occurrence-bound root and nested transformations, retained work/provenance evidence and separately requested bounded independent original-domain irreducibility/completeness certificates.

Search/cache/learning integration and the #748 utility qualification remain open. The modular certificate is sufficient and intentionally incomplete. Multivariate factorization, external mathematical novelty, a qualified search advantage and universal CAS superiority are not established.

Relations: #748, #745, #747, #750, #696, #235, #663.

**Comment by carstenartur** [comment]
## Native general univariate factorization merged in #778; post-merge qualification running

PR #778 was squash-merged as commit `771561e9282b0be45d6b90ebfbfe0180565e64d8` after the exact PR head `779a584b7bd184b1fb4b7d053bf592f7f47e6ec4` passed both authorities in CI run `33123199006`:

```text
checkout-owned Gradle ciCheck                 SUCCESS
complete Maven product and Docker contract   SUCCESS
review threads                                0
merge head continuity                         VERIFIED
```

The merged implementation delivers the bounded native `Z[x]`/`Q[x]` pipeline through:

- deterministic Zassenhaus recombination;
- explicit coefficient bound and `p^k > 2B` precision requirement;
- stable modular-subset and leading-divisor enumeration;
- exact divisibility tests in `Z[x]`;
- deterministic candidate-audit commitments;
- independent product and modular-partition reconstruction;
- rational unit/factor reassembly without decimal conversion;
- typed general native engines for `BigIntegerDomain` and `ExactRationalField`;
- retained multiplicities and one common request-wide Candidate/Work authority.

The final qualification repair addressed repeated nonlinear square-free layers. A later layer may inherit already consumed `hensel.*` work under the same request authority; only those retained Hensel stages may grow monotonically. Selection, Berlekamp and every other prefix stage remain exact. The exact former benchmark failure `(x - 1)^2 (x + 2)^2 (x^2 + 1)` is now an early native-engine regression with multiplicities `2, 2, 1`.

The specialist-only timing presentation is replaced. `A^4 + 4B^4` remains only as `SPECIALIZED_BINARY_QUARTIC_CONTROL`; the primary `GENERAL_UNIVARIATE_CAPABILITY_MATCHED` matrix presents identical common `Z[x]`/`Q[x]` requests to the native general engine and GraalPy/SymPy, with backend-only and verifier-inclusive warm tracks and no relative-winner merge gate.

The engine still issues only backend claims such as `BACKEND_CLAIMED_COMPLETE` or `BACKEND_CLAIMED_IRREDUCIBLE`; `FactorizationVerifier` independently reconstructs exact products. This does not by itself become algorithmically independent original-request completeness or irreducibility evidence.

Post-merge state:

```text
main merge commit                              771561e9282b0be45d6b90ebfbfe0180565e64d8
main checkout-owned CI run                     33126793164
main CI status                                  RUNNING
```

Issue #763 remains open for the exact-rational parser/view handoff, independent original-request completeness/irreducibility evidence, broader held-out qualification, search/learning integration, and optional later LLL/van-Hoeij or additional backends where measured gaps justify them.

**Comment by carstenartur** [comment]
## Parser boundary merged; verified rendering slice opened — 28 August 2026

PR #779 is merged as `ff23fe4f3d453bce2a9348c13d85fbb49545534b`. The parser/view checklist item is therefore complete: parser-issued `ExactParsedTerm` provenance now enters the authoritative `SparsePolynomial<ExactRational>` / request / engine / `FactorizationVerifier` path directly under one non-resettable work authority.

PR #780 is the next exact-head product slice. It implements:

- deterministic exact rendering of verifier-issued rational factors;
- explicit numerator/denominator syntax without `double` or rounded decimals;
- root-occurrence source/literal evidence continuity;
- explicit candidate selection when a report has more than one candidate;
- exact `parseExactTerm` replay and independent reconstruction in the original ring;
- one total ledger across extraction, engine, product verification, rendering, parser input and reconstruction;
- distinct no-candidate, irreducible, unsupported, budget, technical and source-mismatch outcomes;
- focused native `Q[x]` end-to-end qualification.

Nested occurrences and the matched-information/work search comparison remain outside #780 and stay open under this issue and #748. Backend completeness and irreducibility remain claims rather than independent original-domain certificates.

**Comment by carstenartur** [comment]
## Next implementation boundary after #780: nested occurrence reuse

The root-occurrence transformation in #780 is deliberately the mathematical/evidence core. The next slice should extend it to nested AST occurrences without creating a second occurrence model:

```text
parent ExactParsedTerm
  -> existing path-selected subtree occurrence
  -> source-bound exact literal subset for that concrete subtree
  -> ExactParsedFactorizationPipeline
  -> verifier-issued candidate
  -> exact renderer/reparse/reconstruction
  -> existing path-based replacement with staleness guard
  -> one parent-level transformation certificate
```

Required design constraints:

- reuse `TreePosition.path()` and the current text-based staleness guard rather than introducing another positional key;
- keep the parent parser bundle and node-identity literal provenance authoritative while selecting the subtree; do not format/reparse the selected source before factorization;
- extract or share the generic AST path navigation/replacement logic currently owned by `LocalRewriteApplier`, so polynomial transformations and ordinary rule moves cannot drift into duplicate tree-rewrite implementations;
- account path traversal, staleness validation, subtree extraction/factorization, rendering/reparse and parent replacement under one outer non-resettable authority;
- preserve original parent syntax and selected occurrence separately from canonical replacement syntax;
- bind the same transformation identity to on-demand search, graph/replay evidence and later verifier-derived macro replay;
- reject stale, substituted, missing or multiply addressed occurrences fail-closed.

Qualification should include root versus nested equivalence, repeated equal subtrees at different paths, stale-position rejection, source-literal subset continuity, function arguments and ordered binary children, invalid paths, unchanged siblings, deterministic certificates and budget exhaustion during path traversal or parent reconstruction.

**Comment by carstenartur** [comment]
## Fortschreibung am 28. August 2026

Der Wurzel-Transformationsslice ist jetzt tatsächlich geliefert:

- **#780 wurde als `bc992a3811b8b202b31da533341a4770f62a4007` nach `main` gemergt.** Verifier-ausgestellte exakte rationale Faktoren werden deterministisch gerendert, erneut über `parseExactTerm` geparst, im ursprünglichen Ring rekonstruiert und nur bei einer strukturell geänderten Ersatzsyntax als Transformation ausgegeben. `NO_CHANGE` verhindert Identitätskanten; Backend-Claims bleiben von unabhängiger Evidence getrennt.

Die verschachtelte Integration wurde in zwei bewusst kleinere, nicht als geliefert gezählte Slices getrennt:

1. **#782 – parsergebundene AST-Quellbereiche.** Ein konkreter parsererzeugter Knoten erhält einen identitätsgebundenen halb offenen `SourceRange`; exakte Literal-Evidence bleibt die einzige numerische Autorität. Der finale Branch ist ein Commit direkt auf #780. Er lehnt fremde Range-Einträge, wiederverwendete Knotenidentitäten, unvollständige Wurzelabdeckung, vertauschte/überlappende Kindbereiche, Zahlen ohne exakte Literal-Evidence und gefälschte Unary-Minus-Ausnahmen fail-closed ab. Die Baumvalidierung ist iterativ und wird mit einem 12.000-Summanden-Ausdruck charakterisiert. **Dieser Slice bleibt bis zum grünen exakten Head und Merge offen.**

2. **#783 – exakte Teilbaumprojektion.** Ein path-selektiertes, source-gestütztes Vorkommen wird ohne numerischen Formatter-/Reparse-/`double`-Umweg in ein lokales `ExactParsedTerm` projiziert. AST- und Literal-Evidence-Identitäten bleiben erhalten; nur die Source-Ranges werden in lokale Koordinaten verschoben. Formattertext dient ausschließlich als begrenzter Stalenessschutz. **Der PR ist gestapelt auf #782 und bleibt bis zu dessen Merge, Retarget auf `main` und vollständiger Qualifikation ein Draft.**

Nach #783 bleibt für die geschlossene verschachtelte Produktkante weiterhin offen:

```text
projected ExactParsedTerm
  -> ExactParsedFactorizationPipeline
  -> FactorizationVerifier
  -> #780 rendering/reparse/reconstruction
  -> replacement at exactly the authorized path
  -> root replay plus context/staleness verification
```

Projektions-, Faktorisierungs-, Rendering-, Reparse-, Ersetzungs- und Replayarbeit müssen dabei in einer gemeinsamen nicht zurücksetzbaren Gesamtbilanz zusammengeführt werden. Aus #782 oder #783 wird noch keine erfolgreiche verschachtelte Faktorisierung, Standard-Suchaktivierung oder unabhängige Vollständigkeits-/Irreduzibilitätsaussage abgeleitet.

**Comment by carstenartur** [comment]
Structural prerequisite update: #801 has merged as `c008fecfb5fe4ec69032a4221027184745b227d9`. `TreePosition` is now the shared iterative selection/replacement authority, with typed invalid-versus-absent outcomes, object-identity preservation for untouched siblings, actual stale-snapshot tests and an 8,000-edge path test. #785 has been rebuilt as one commit (`02b3c7b4148b4e778ae4622e7b942510bf1eb236`) directly on that exact `main`; its source tree is byte-identical to the previously fully green stacked tree and is undergoing an independent direct-on-main qualification. The old #784 wrapper was closed as superseded without discarding capability.

**Comment by carstenartur** [comment]
## Status update — 29 August 2026

The product-occurrence boundary is now delivered on `main`.

- #780 merged the verifier-bound exact **root occurrence** transformation as `bc992a3811b8b202b31da533341a4770f62a4007`.
- #802 merged the exact **selected nested occurrence** transformation as `0003a7a57b833bc8680f5132b65b703ba9902864` after both review threads and all independent Gradle, JMH/SymPy, Maven/product/Docker and converged checks passed on the exact head.

Accordingly, every item currently listed in sections **C. Root-occurrence verified transformation** and **D. Nested occurrence integration** is implemented. The merged nested path uses parser-issued evidence, the shared iterative `TreePosition` selection/replacement authority, explicit missing/stale/invalid outcomes, retained surrounding identity, one non-resettable work authority, bounded structural replay and a stable content-addressed transformation identity.

The issue remains open for the genuinely distinct work that was not smuggled into those PRs:

1. section E — separately named independent original-domain completeness/irreducibility certificates;
2. section F — search, cache and learning integration (the first typed cache/replay boundary is being qualified in #786);
3. section G — frozen comparative evidence and reproduction.

The current claim boundary may now include exact reconstructed root and selected nested transformations. It still must not claim independent original-domain completeness, a qualified search advantage, multivariate factorization, external novelty or general CAS superiority.

**Comment by carstenartur** [comment]
Independent original-domain certification is now delivered in two merged slices:

- #940 adds the bounded independent source-irreducibility verifier for univariate `Z[x]` and `Q[x]`.
- #941 applies that verifier independently to every distinct factor of an exact-product candidate, requires remainder one, and issues request-/source-bound completeness evidence before authorizing `COMPLETE_FACTORIZATION`.

The #941 head passed checkout-local Gradle, complete Maven/Docker, isolated SymPy, isolated JMH, and aggregate `ciCheck` in [CI run 34149917453](https://github.com/carstenartur/Regelsuche/actions/runs/34149917453). Missing modular witnesses and exhausted work remain fail-closed and inconclusive; this is intentionally a bounded sufficient certificate, not a decision-complete procedure.

Issue #763 remains open for nested occurrence integration, stable cross-surface transformation identity, search/cache qualification, and later expansion.
